### ISSUE TITLE
Reduce BNet traffic

### ISSUE THREAD

**Issue by Chalsean** [Chalsean/XFaction#207]

**Comment by Chalsean** [comment]
Currently if the origin of the guild chat does not have a bnet friend online, he/she will broadcast on local channel.  Other users of the same faction will recognize that the message has not been sent to the other faction and forward to 1 of their friends.

Under extreme load (100+ users) what this can cause it 20 or more Alliance users to hammering someone like Bic with the same message.

The idea is to find a way to reduce this load.  Either by the origin of the message selecting which BNet nodes should forward for them or by doing randomization (like if 20 Alliance nodes are online, only have 1/3 of them forward the message).

**Comment by mesato** [comment]
While no instance of this issue has come into play, might as well try to get ahead of it if there's bandwidth.

**Comment by Chalsean** [comment]
- Switched to better compression library
- Removed duplicate message header information
- More granularity in setting packet size
- Added functionality to play percentage game if your target (realm/faction) node count is above a threshold
