### ISSUE TITLE
Links bug

### ISSUE THREAD

**Issue by Chalsean** [Chalsean/XFaction#213]
Theres been multiple times now where my two accounts are out of sync on the link.  Alliance toon sees the Horde toon and knows it has a link.  But the Horde toon does not see the Alliance toon.  Need to investigate the ping logic.

**Comment by Chalsean** [comment]
this was a race condition between ping and event driven (bnet friend).  updated code to rescan friends if receiving a bnet whisper and friend is not in cache

**Comment by waggz81** [comment]
We just started testing this addon and we're having the same issue, on horde toons it only shows the horde realms but for alliance it shows both. Data seems to be able to send from alliance to horde but nothing is getting from horde to alliance. Is there a working version with this fix? I tried the 3.4 branch but seems it has some issues still.

**Comment by Chalsean** [comment]
Would need to know a few things in order to help:

What guilds are you trying to setup?
What does the guild info look like for both guilds?
How many links are active when you're testing?
What version is everyone using?  3.3 reworked the BNet communication and is
not backwards compatible

**Comment by waggz81** [comment]
We were all on 3.3.0 when this was happening. We updated to the 3.3.2 release today and now it's not even working between guilds on same realm and faction. I only see possible links for the horde guilds on both alliance and horde toons but no connections are listed when they should be.

Our current settings (minus channel info string)
```
XFn:Death Jesters and Zeroes to Heroes:djzth
XFg:60:1:Zeroes to Heroes:ZtH
XFg:60:1:Death Jesters:DJ
XFg:60:1:Little Heroes:LH
XFg:60:1:Mini Heroes:MH
XFg:60:2:Zeroes to Hordies:ZtHH
XFg:60:2:Evil Death Jesters:EDJ
XFg:57:2:Zeroes to Heroes:ZtHI
```

**Comment by Chalsean** [comment]
it wont show any links between members of the same realm/faction, unless you mean it doesnt show alliance<->horde.  keep in-mind that if someone is incognito (appear offline) they cannot be used as a BNet bridge

**Comment by Chalsean** [comment]
you did setup a channel right?  i dont need to know the password, just validating that you did that step

**Comment by Chalsean** [comment]
feel free to ping me on discord Chalsean#7679

**Comment by Chalsean** [comment]
found a nasty bug introduced with 3.3.0, yanked all 3.3 line and published 3.3.4.  it likely was the issue, my guild brought it to my attention about an hour ago

**Comment by waggz81** [comment]
> you did setup a channel right? i dont need to know the password, just validating that you did that step

Yes, I left that one out. We had several bnet links but they only showed up on alliance guilds, when using 3.3.0. We will update to new release and test again tomorrow. Added you on discord.

**Comment by waggz81** [comment]
Just wanted to wrap up this discussion, there was an error in the setup page that has now been fixed to designate alliance and horde guilds. Changing to 
```
XFn:Death Jesters and Zeroes to Heroes:djzth
XFg:60:A:Zeroes to Heroes:ZtH
XFg:60:A:Death Jesters:DJ
XFg:60:A:Little Heroes:LH
XFg:60:A:Mini Heroes:MH
XFg:60:H:Zeroes to Hordies:ZtHH
XFg:60:H:Evil Death Jesters:EDJ
XFg:57:H:Zeroes to Heroes:ZtHI
```
has fixed our issue. Thanks again!
