### ISSUE TITLE
Add realm ID lookup link to wiki guild setup section

### ISSUE THREAD

**Issue by waggz81** [Chalsean/XFaction#232]
I can't figure out how to make a PR for a a wiki page or I would do that but...

It would be nice to have a link to the realm ids in the instructions, something like 
`Server IDs can be found [here](https://github.com/Chalsean/XFaction/blob/main/XFaction/Libraries/LibRealmInfo/LibRealmInfo.lua#L226)`

I struggled for a moment with a "Stormrage isn't a supported realm" on the initial setup because I took the instructions as written to mean that the 'index' was just an index of the number of different realms configured. I had to look around in the code for a minute to figure out that wasn't the case and find the table in the librealminfo lib.

**Comment by Chalsean** [comment]
Thx for feedback, have updated with the following:

You can find your realm id by running the following command while logged into the WoW realm in question: /dump GetRealmID(), GetRealmName()
