### ISSUE TITLE
Some achievements not passing bnet link

### ISSUE THREAD

**Issue by waggz81** [Chalsean/XFaction#263]
We had some achievements not get passed over a bnet link, though this might be intentional on your part. 

Two players on horde, with active bnet link, this is what horde saw:
![image](https://user-images.githubusercontent.com/20745474/182001831-e2a6862d-544d-4882-808a-c0124a8f5c93.png)

I didn't see any achievements on alliance side, just their chat about it. I saw previous achievements from horde side earlier in the day though.

Everyone involved was up to date with 3.5.2:
![image](https://user-images.githubusercontent.com/20745474/182001790-30b55469-e303-4fd9-9a52-8aa7c0f42690.png)

**Comment by Chalsean** [comment]
The Explore ones were explicitly filtered out.  There was a period where
traffic was a concern and people were getting dc'd.  The problem
revolves around the shadowlands map and shotgunning 10+ achievements all at
once during high traffic times.  I can remove the filter to see how it
behaves now that the addon is more stable.

**Comment by Chalsean** [comment]
3.5.4

**Comment by Chalsean** [comment]
sorry gotta reopen this, i missed the code checkin

**Comment by joshwaggoner-olo** [comment]
oh I didn't mean to say it should be there, I'm in agreement it's dumb spam from those toys. just want sure if they were intentionally left out or some kind of unexpected limit was breaking it. those toys shouldn't give those achievements anyway, so dumb.

**Comment by joshwaggoner-olo** [comment]
oops wrong gh account, it's me waggz

**Comment by Chalsean** [comment]
based on user feedback will close out this ticket as not required
