### ISSUE TITLE
Suppress errors when logging on to guild without xfaction config

### ISSUE THREAD

**Issue by waggz81** [Chalsean/XFaction#272]
Rather than having to disable for all individual toons not in an XFaction guild, could this error be suppressed if no config is found in ginfo?

```XFaction: Failed to start properly. Interface\AddOns\XFaction\Handlers\TimerEvent.lua:214: bad argument #2 to 'error' (number expected, got string)```

**Comment by Chalsean** [comment]
i can provide an option for this but wont be suppressing errors by default.  reason being is that there are valid instances where users should see those errors, rather than blindly assuming its working properly.  thinking first time setups, if it says nothing, then they dont know its not working

**Comment by waggz81** [comment]
I'm just saying this is not a good error to provide feedback. Definitely agree it should have some sort of notice that no config was found, but showing some lua interface error isn't helpful.

**Comment by Chalsean** [comment]
fair, i can also look at cleaning up the error message itself

**Comment by Chalsean** [comment]
3.7.2 has the updated error message, ill try to get the disable config option in the next build

**Comment by Chalsean** [comment]
implemented in 3.8
