### ISSUE TITLE
Automate BNet mesh

### ISSUE THREAD

**Issue by Chalsean** [Chalsean/XFaction#285]
BNet seems to have an API to auto send/accept/remove friends, possible to automate the BNet mesh as well as party/raid invites..?

- BNSendFriendInvite
- BNAcceptFriendInvite
- BNSetFriendNote
- BNRemoveFriend
- BNSetBlocked (?)

Possible to auto group them?

**Comment by waggz81** [comment]
ah dang i got excited about this for a second :)

**Comment by Chalsean** [comment]
Unfortunately theres too many protected strings in the BNet calls.  So there's no way to associate a friend invite with anything having to do with the guild or addon.  It would just be blindly accepting any/all friend invites.
