### ISSUE TITLE
Can't debug the cause for our confederacy not working

### ISSUE THREAD

**Issue by Fyurie** [Chalsean/XFaction#311]
Apologies for the vague title, I'm struggling to figure out exactly what's up to even describe the issue better.

To get to it: I've been trying since prepatch hit to work out why our confederate no longer functions as it did before the patch hit. I noticed after turning on the Metrics DT that I was being presented with this: https://puu.sh/Jq9oe.png

I saw in the Wiki that grabbing _debuglog to see what was going on behind the scenes would be a worthwhile idea, and that presented me with this: https://puu.sh/Jq9oY.txt

(I'd put it in a code block but a thousand lines of log seemed a bit brutal for a github post's readability, haha)

I'm kind of at a loss at the moment since I've confirmed that we have an otherwise properly set up pair of guild info tabs, along with at least two players—on each faction—with the most up-to-date and fresh install of EK XFaction. We're also definitely Bnet friends and appearing online.

I couldn't find any other means for support relating to the addon since the EK discord seems to be centered around its own activities, so I'm resorting to making an issue ticket to see if this is something deeper or if I'm just missing something obvious. I can share any other necessary information as requested.

**Comment by Chalsean** [comment]
what does your guild info look like?  specifically the XFn and XFg lines

**Comment by Fyurie** [comment]
```
XFn:Gorilla Warfare:GW
XFg:1306:H:Gorilla Warfare:GW
XFg:1306:A:Chimpanzee Combat:CC
```

**Comment by Chalsean** [comment]
offhand i cant say, your config looks right. ill need to park a toon in your guild and probably bnet friend someone to debug. im going to guess its a realm not listed in the LibRealm library. its the only location to get a realm superset but stopped being maintained

**Comment by Fyurie** [comment]
Interesting...

Well, that can be arranged at whatever your earliest convenience is. I'm reachable at Fyurie#2454 on Bnet to arrange such a thing.

**Comment by Fyurie** [comment]
Not sure if it helps at all, but I've been watching it regularly since first making this ticket, and this appears to be the single recurring error message in all that time, so I've singled it out for easier reference.

```
| ID| Time| Cat| Vrb| Message |
| --- | --- | --- | --- | ---  |
| 673| 10-31 12:31:36| FriendCollection| 2| ...terface/AddOns/XFaction/Network/FriendCollection.lua:152: Interface/AddOns/XFaction/Network/Friend.lua:93: argument must be Target object |
| 674| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:37: in function `Warn' |
| 675| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:162: in function `catchBlock' |
| 676| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch' |
| 677| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:161: in function `CheckFriend' |
| 678| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:169: in function <...terface/AddOns/XFaction/Network/FriendCollection.lua:167> |
| 679| 10-31 12:31:36| FriendCollection| 2| [string "=[C]"]: in function `pcall' |
| 680| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try' |
| 681| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:167: in function `CheckFriends' |
| 682| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/BNet.lua"]:93: in function <Interface/AddOns/XFaction/Network/BNet.lua:87> |
| 683| 10-31 12:31:36| FriendCollection| 2| [string "=[C]"]: in function `pcall' |
| 684| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try' |
| 685| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/BNet.lua"]:87: in function `_Function' |
| 686| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Wrappers/EventCollection.lua"]:25: in function <...terface/AddOns/XFaction/Wrappers/EventCollection.lua:21> |
```

**Comment by Effeh** [comment]
We were having the same trouble; commenting out line 93 in /Handlers/Friend.lua seemed to fix the problem for us, if that gives you any leads, Chalsean.

**Comment by Chalsean** [comment]
> Interesting...
> 
> Well, that can be arranged at whatever your earliest convenience is. I'm reachable at Fyurie#2454 on Bnet to arrange such a thing.
> 
> Edit: I did check the packaged LibRealm file after you mentioned it: Tarren Mill-EU is listed there, along with its connection to Dentarg-EU, if that counts for anything.

hmm, then i think its more a question of the realm in which your friend is on and whether thats in the library. ill provide a debug copy to try to isolate which friend is causing the issue

**Comment by Chalsean** [comment]
> We were having the same trouble; commenting out line 93 in /Network/Friend.lua seemed to fix the problem for us, if that gives you any leads, Chalsean.

appreciate the info!

**Comment by Chalsean** [comment]
> Not sure if it helps at all, but I've been watching the debug log regularly since first making this ticket, and this appears to be the single recurring error message in all that time, so I've singled it out for easier reference.
> 
> ```
> | ID| Time| Cat| Vrb| Message |
> | --- | --- | --- | --- | ---  |
> | 673| 10-31 12:31:36| FriendCollection| 2| ...terface/AddOns/XFaction/Network/FriendCollection.lua:152: Interface/AddOns/XFaction/Network/Friend.lua:93: argument must be Target object |
> | 674| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:37: in function `Warn' |
> | 675| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:162: in function `catchBlock' |
> | 676| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch' |
> | 677| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:161: in function `CheckFriend' |
> | 678| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:169: in function <...terface/AddOns/XFaction/Network/FriendCollection.lua:167> |
> | 679| 10-31 12:31:36| FriendCollection| 2| [string "=[C]"]: in function `pcall' |
> | 680| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try' |
> | 681| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/FriendCollection.lua"]:167: in function `CheckFriends' |
> | 682| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/BNet.lua"]:93: in function <Interface/AddOns/XFaction/Network/BNet.lua:87> |
> | 683| 10-31 12:31:36| FriendCollection| 2| [string "=[C]"]: in function `pcall' |
> | 684| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try' |
> | 685| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Network/BNet.lua"]:87: in function `_Function' |
> | 686| 10-31 12:31:36| FriendCollection| 2| [string "@Interface/AddOns/XFaction/Wrappers/EventCollection.lua"]:25: in function <...terface/AddOns/XFaction/Wrappers/EventCollection.lua:21> |
> ```

if you could, please insert the following line in Network/FriendCollection between lines 129 and 130 and send me the results:

XFG:DataDumper(ObjectName, accountInfo)

> 		accountInfo.ID = inKey
>		XFG:DataDumper(ObjectName, accountInfo)
>		local canLink, target = CanLink(accountInfo)

**Comment by Fyurie** [comment]
It's pushing so much data to debuglog that I'm getting frame stutters, but I found this error a few times buried in the hundreds of thousands of lines of log it's spewing out.

![image](https://user-images.githubusercontent.com/207523/199314374-9f05a665-def0-41b9-9524-768eed4ddd02.png)

**Comment by Fyurie** [comment]
![image](https://user-images.githubusercontent.com/207523/199336524-1c85297d-b20c-430f-af4e-6f9c1fc07e9b.png)

Got an example of what you're requesting, I think...?

**Comment by Chalsean** [comment]
perfect, great job.  now ill see if i can replicate the issue on my end

**Comment by Chalsean** [comment]
looks like it is the LibRealm altho a new bug i was unaware of, it doesnt like the same server being in 2 regions. Tarren Mill's connected realm (Dentarg) is both US and EU. ill work on a fix

**Comment by Fyurie** [comment]
Looking forward to it, hopefully it's nothing too painful.

**Comment by Chalsean** [comment]
thats unforunate, try 4.1.1

**Comment by Fyurie** [comment]
![Uploading image.png…]()

 Looking good...?

**Comment by Chalsean** [comment]
yes thats what it should look like

**Comment by Fyurie** [comment]
Hell yeah.

**Comment by Chalsean** [comment]
thx for all your time and patience, could not have fixed it without your help  :)
