### ISSUE TITLE
Not seeing my own achieves in guild chat

### ISSUE THREAD

**Issue by FortyOneNY** [Chalsean/XFaction#313]
This is a weird one because no errors are thrown (I use bugsack and buggrabber) -- **When I earn an achievement, I do not see it via the Guild Achievement Announce setting for the chat windows**; I only see it in the Achievement Announce setting where any nearby char's achieves are shown. Other people can usually see my achievements in guild chat, but yesterday I also used all the scouting maps and no one complained about the achieve spam that generates. I have no issues seeing other people's achieves via the Guild Achieve Announce - they all come through okay. My XFaction settings are set to show achieves. The only settings I disabled were the ones related to showing faction icons.

I did a fresh install of XFaction and deleted all of its saved variables and backups. I then proceeded to test with no addons, xfaction only (plus the bug tools), xfaction plus the chat mod I use (BasicChatMods on curse), everything but xfaction, and everything. The only times I never saw my own achievements show up in guild chat was when I had XFaction enabled, and during those times I walked across the hall to check my husband's chat and they were showing up to him.

Since it may be relevant, I am a part of the DJ/ZtH confederate on Stormrage/Illidan. This occurred both on my Stormrage and Illidan characters.

**Comment by Chalsean** [comment]
the exploring achievements are specifically filtered out to avoid noise in large guilds

**Comment by FortyOneNY** [comment]
I thought maybe that was the case for those specifically, but the issues still happens with any of my other achieves (level X0, Renowned, Into The Wild Blue Yonder, Welcome to Draenor, etc).

**Comment by Chalsean** [comment]
k, ill see if i can replicate the issue

**Comment by Chalsean** [comment]
please try beta build 4.1.5 and see if it fixes the issue for you

**Comment by FortyOneNY** [comment]
Just installed the beta build then briefly tested by logging in a character that hadn't been logged in yet for the anniversary, and I saw my 18th anniv achieve in the guild announce channel! I can do more testing in the evening (eastern US time) once I'm home again, as I'm sure I'll gain some achievements while leveling up some alts - but it looks good!

Thank you again for looking into this!

**Comment by FortyOneNY** [comment]
I just got some achieves while questing through WoD zones and they showed up in guild chat. I think you solved this one!

**Comment by Chalsean** [comment]
great, thx for testing.  ill promote the build to production
