### ISSUE TITLE
BNet "Unable to Identify friends"

### ISSUE THREAD

**Issue by Hyphie24** [Chalsean/XFaction#325]
Looking to get some help, have a few guilds on Aerie Peak, that are on both Horde & Alliance. We're transitioning from Greenwall to Xfaction and we're running into trouble. We tried everything by the wiki & FAQ and can't seem to figure out what our issue is. Tried across 3 different realms (not using Aerie Peak) and that worked perfectly fine, but using any guilds on Aerie peak we get this debuglog

![xfaction](https://user-images.githubusercontent.com/31455641/202927859-d6b75e04-40a4-4f94-9490-50a52b5b0cdb.png)

Would like to get any information as to what we're possibly doing wrong

We are using 6 people, all of us are BNet friends and have been for 6 months+

**Comment by Chalsean** [comment]
hello, looks like i had the connected realm wrong for aerie peak (its ulduar). i just pushed a beta build (4.1.15) to github and curseforge.  please give it a shot and let me know if it fixes it for you

**Comment by Hyphie24** [comment]
worked perfectly, thank you so much!

**Comment by Chalsean** [comment]
no worries, sorry about that
