### ISSUE TITLE
Alt name/team inconsistencies

### ISSUE THREAD

**Issue by waggz81** [Chalsean/XFaction#327]
Can you clarify on the alt names config? Seems like not all members are being handled the same way in our alt guilds, we have been using `[ZtH-J] Mainname` as the public note as was discussed previously, but in the config guide now it says to just use the team initial? With the way we are doing it now for myself, I see the main name but unknown team. If I just use `[J]` then it shows the team name but not the main name in the datatext. Then again, there are some users where neither of those shows a team name or main name with either configuration. (You can check the notes yourself if you'd like, this particular one is `Johnlock` in Mini Heroes - Stormrage where you have a toon.) Let me know if there's any particular debug output you want, or ping me on discord if you want to test things live.

**Comment by Chalsean** [comment]
for mains, just use the team initial.  for alts, its [team initial-guild initials] name.  where all information is for the main character.  so if my main is in an alliance guild and im logged into an alt on the horde side, [J-ZtH] Chalsean would be my text

**Comment by Chalsean** [comment]
i did notice that you have Nomis defined twice in your guild notes and D is in someones notes but not defined

**Comment by waggz81** [comment]
Ha thanks for catching that. Yeah one of those should be Death Jesters. That's from me trying to rewrite the config out when the serialization changed. The J team is fake, we added that to work around the alt names to begin with. Is that something we still need now?

**Comment by Chalsean** [comment]
if you want their alt name to show, the way it is coded today youd need to supply a team initial, guild initials (where the main is) in brackets and then the main name.  example:  [Y-EKA] Chalsean is my notes on alts.  im not wild about the standard but do need to conform to it for EK.  if theres a different standard you would prefer, i can look to see what it would take to implement, i just have to be cognizant to not break current functionality

**Comment by waggz81** [comment]
yeah no worries not worth the effort, what we have now works (when I tell people to do it correctly 🤣 )  I just remember when we were chatting about it originally you said it was probably going to change but wasn't sure if it had or not. The tagging thing seems interesting, I'll comment more there as this seems resolved for me now. (Resolved as in I'm dumb and was doing it backwards the whole time.)
