### ISSUE TITLE
Upgraded to most recent version, confederation 100% broken

### ISSUE THREAD

**Issue by TKardinal** [Chalsean/XFaction#336]
We're on Aerie Peak, have been using XFaction for a month or so without issue.

After we upgrade to the most recent version, our databrokers show no information, and we cannot communicate across guilds at all.

Here's some relevant debug output.  We did check to ensure that all the connected realm IDs were correct, and they appear to be.  Just in case that change was somehow not merged into this version.

I'll be watching all night tonight so let me know if I can provide any other diagnostic information.

Thanks for making this available to others!

ID;Time;Cat;Vrb;Message;
1;12-12 18:24:46;;;Log for 'XFaction' created;
2;12-12 18:24:46;;;Format for log 'XFaction' is 'default';
3;12-12 18:24:46;Event;4;Started event listener [Config Loaded] for [XFCONFIG_LOADED];
4;12-12 18:24:46;Event;3;Registered to receive [Config Loaded:XFCONFIG_LOADED] events;
5;12-12 18:24:46;Event;4;Started event listener [ElvUI Load] for [XFADDON_LOADED];
6;12-12 18:24:46;Event;3;Registered to receive [ElvUI Load:XFADDON_LOADED] events;
7;12-12 18:24:46;Event;4;Started event listener [WIM Load] for [XFADDON_LOADED];
8;12-12 18:24:46;Event;3;Registered to receive [WIM Load:XFADDON_LOADED] events;
9;12-12 18:24:46;Event;4;Started event listener [AddonEvent] for [ADDON_LOADED];
10;12-12 18:24:46;Event;3;Registered to receive [AddonEvent:ADDON_LOADED] events;
11;12-12 18:24:46;Initialize;3;XFaction version [4.2.4];
12;12-12 18:24:46;RegionCollection;3;Initialized player region [1:US];
13;12-12 18:24:46;FactionCollection;3;Initialized faction [1:Alliance];
14;12-12 18:24:46;FactionCollection;3;Initialized faction [2:Horde];
15;12-12 18:24:46;FactionCollection;3;Initialized faction [3:Neutral];
16;12-12 18:24:46;RealmCollection;3;Initialized player realm [1284:Aerie Peak];
17;12-12 18:24:46;Event;4;Started event listener [Setup Realms] for [XFCACHE_LOADED];
18;12-12 18:24:46;Event;3;Registered to receive [Setup Realms:XFCACHE_LOADED] events;
19;12-12 18:24:46;Realm;4;-------------------------------------;
20;12-12 18:24:46;Realm;4;  key (string): Aerie Peak;
21;12-12 18:24:46;Realm;4;  name (string): Aerie Peak;
22;12-12 18:24:46;Realm;4;  initialized (boolean): true;
23;12-12 18:24:46;Realm;4;  ID (number): 1284;
24;12-12 18:24:46;Realm;4;  apiName (nil): nil;
25;12-12 18:24:46;Realm;4;  isTargeted (boolean): false;
26;12-12 18:24:46;Realm;4;  connectedRealmCount (number): 1;
27;12-12 18:24:46;Realm;4;* connectedRealm [1426];
28;12-12 18:24:46;ZoneCollection;3;Initialized continent [Pandaria];
29;12-12 18:24:46;ZoneCollection;3;Initialized continent [Draenor];
30;12-12 18:24:46;ZoneCollection;3;Initialized continent [Broken Isles];
31;12-12 18:24:46;ZoneCollection;3;Initialized continent [Zandalar];
32;12-12 18:24:46;ZoneCollection;3;Initialized continent [Kul Tiras];
33;12-12 18:24:46;ZoneCollection;3;Initialized continent [Argus];
34;12-12 18:24:46;ZoneCollection;3;Initialized continent [Eastern Kingdoms];
35;12-12 18:24:46;ZoneCollection;3;Initialized continent [Kalimdor];
36;12-12 18:24:46;ZoneCollection;3;Initialized continent [Outland];
37;12-12 18:24:46;ZoneCollection;3;Initialized continent [Northrend];
38;12-12 18:24:46;ZoneCollection;3;Initialized continent [Nazjatar];
39;12-12 18:24:46;ZoneCollection;3;Initialized continent [Resonant Peaks];
40;12-12 18:24:46;ZoneCollection;3;Initialized continent [The Shadowlands];
41;12-12 18:24:46;ZoneCollection;3;Initialized zone [?];
42;12-12 18:24:46;Hook;4;Started hook [ReloadUI];
43;12-12 18:24:46;Hook;3;Hooked function ReloadUI;
44;12-12 18:24:46;Event;4;Started event listener [Logout] for [PLAYER_LOGOUT];
45;12-12 18:24:46;Event;3;Registered to receive [Logout:PLAYER_LOGOUT] events;
46;12-12 18:24:46;Event;4;Started event listener [LoadScreen] for [PLAYER_ENTERING_WORLD];
47;12-12 18:24:46;Event;3;Registered to receive [LoadScreen:PLAYER_ENTERING_WORLD] events;
48;12-12 18:24:46;SystemEvent;3;Created CHAT_MSG_SYSTEM event filter;
49;12-12 18:24:46;Timer;4;Started timer [Login] for [1] seconds;
50;12-12 18:24:46;Event;4;Started event listener [DTGuild Init] for [XFINIT];
51;12-12 18:24:46;Event;3;Registered to receive [DTGuild Init:XFINIT] events;
52;12-12 18:24:46;Event;4;Started event listener [DTLinks Init] for [XFINIT];
53;12-12 18:24:46;Event;3;Registered to receive [DTLinks Init:XFINIT] events;
54;12-12 18:24:46;Event;4;Started event listener [DTTokenPLAYER_ENTERING_WORLD] for [PLAYER_ENTERING_WORLD];
55;12-12 18:24:46;Event;3;Registered to receive [DTTokenPLAYER_ENTERING_WORLD:PLAYER_ENTERING_WORLD] events;
56;12-12 18:24:46;DTToken;3;Registered for PLAYER_ENTERING_WORLD events;
57;12-12 18:24:46;Event;4;Started event listener [DTTokenPLAYER_LOGIN] for [PLAYER_LOGIN];
58;12-12 18:24:46;Event;3;Registered to receive [DTTokenPLAYER_LOGIN:PLAYER_LOGIN] events;
59;12-12 18:24:46;DTToken;3;Registered for PLAYER_LOGIN events;
60;12-12 18:24:46;Event;4;Started event listener [DTTokenTOKEN_MARKET_PRICE_UPDATED] for [TOKEN_MARKET_PRICE_UPDATED];
61;12-12 18:24:46;Event;3;Registered to receive [DTTokenTOKEN_MARKET_PRICE_UPDATED:TOKEN_MARKET_PRICE_UPDATED] events;
62;12-12 18:24:46;DTToken;3;Registered for TOKEN_MARKET_PRICE_UPDATED events;
63;12-12 18:24:46;Timer;4;Started timer [TokenTimer] for [60] seconds;
64;12-12 18:24:46;DTToken;3;New token price [166463];
65;12-12 18:24:46;ExpansionCollection;3;Initialized expansion [1:Retail];
66;12-12 18:24:46;ExpansionCollection;3;Initialized expansion [2:Classic];
67;12-12 18:24:46;Initialize;3;WoW client version [Retail:10.0.2];
68;12-12 18:24:46;AddonEvent;3;Addon is loaded and enabled [XFaction];
69;12-12 18:24:46;AddonEvent;3;Initializing cache;
70;12-12 18:24:46;Config.General;3;Configs loaded;
71;12-12 18:24:49;TimerEvent;4;Guild info is loaded, proceeding with setup;
72;12-12 18:24:49;Timer;4;Stopped timer [Login];
73;12-12 18:24:49;GuildCollection;3;Initialized guild [Eme:Convert to Raid Emeriss];
74;12-12 18:24:49;GuildCollection;3;Initialized guild [Kaz:Convert to Raid Kazzak];
75;12-12 18:24:49;GuildCollection;3;Initialized guild [Moo:Convert to Raid Moonfang];
76;12-12 18:24:49;GuildCollection;3;Initialized guild [Nal:Convert to Raid Nalak];
77;12-12 18:24:49;GuildCollection;3;Initialized guild [Mob:Convert to Raid Mobus];
78;12-12 18:24:49;GuildCollection;3;Initialized guild [Gall:Convert to Raid Galleon];
79;12-12 18:24:49;GuildCollection;3;Initialized guild [Azu:Convert to Raid Azuregos];
80;12-12 18:24:49;GuildCollection;3;Initialized guild [Ome:Convert to Raid Omen];
81;12-12 18:24:49;GuildCollection;3;Initialized guild [Ord:Convert to Raid Ordos];
82;12-12 18:24:49;GuildCollection;3;Initialized guild [Sha:Convert to Raid Sha];
83;12-12 18:24:49;GuildCollection;3;Initialized guild [Kor:Convert to Raid Koranos];
84;12-12 18:24:49;GuildCollection;3;Initialized guild [Zek:Convert to Raid Zekhan];
85;12-12 18:24:49;Confederate;3;Initialized confederate Convert to Raid <CtR>;
86;12-12 18:24:49;TimerEvent;1;...rface/AddOns/XFaction/Confederate/TeamCollection.lua:26: bad argument #1 to 'pairs' (table expected, got nil);
87;12-12 18:24:49;TimerEvent;1;[string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:29: in function `Error';
88;12-12 18:24:49;TimerEvent;1;[string "@Interface/AddOns/XFaction/Handlers/TimerEvent.lua"]:95: in function `catchBlock';
89;12-12 18:24:49;TimerEvent;1;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch';
90;12-12 18:24:49;TimerEvent;1;[string "@Interface/AddOns/XFaction/Handlers/TimerEvent.lua"]:94: in function <Interface/AddOns/XFaction/Handlers/TimerEvent.lua:21>;
91;12-12 18:24:49;TimerEvent;1;;
92;12-12 18:24:49;Event;4;Stopped event listener [AddonEvent] for [ADDON_LOADED];
93;12-12 18:24:49;Event;4;Stopped event listener [Config Loaded] for [XFCONFIG_LOADED];
94;12-12 18:24:49;Event;4;Stopped event listener [ElvUI Load] for [XFADDON_LOADED];
95;12-12 18:24:49;Event;4;Stopped event listener [Logout] for [PLAYER_LOGOUT];
96;12-12 18:24:49;Event;4;Stopped event listener [LoadScreen] for [PLAYER_ENTERING_WORLD];
97;12-12 18:24:49;Event;4;Stopped event listener [DTTokenTOKEN_MARKET_PRICE_UPDATED] for [TOKEN_MARKET_PRICE_UPDATED];
98;12-12 18:24:49;Event;4;Stopped event listener [DTTokenPLAYER_LOGIN] for [PLAYER_LOGIN];
99;12-12 18:24:49;Event;4;Stopped event listener [Setup Realms] for [XFCACHE_LOADED];
100;12-12 18:24:49;Event;4;Stopped event listener [WIM Load] for [XFADDON_LOADED];
101;12-12 18:24:49;Event;4;Stopped event listener [DTGuild Init] for [XFINIT];
102;12-12 18:24:49;Event;4;Stopped event listener [DTLinks Init] for [XFINIT];
103;12-12 18:24:49;Event;4;Stopped event listener [DTTokenPLAYER_ENTERING_WORLD] for [PLAYER_ENTERING_WORLD];
104;12-12 18:24:49;Hook;4;Stopped hook [ReloadUI];
105;12-12 18:24:49;Timer;4;Stopped timer [Ping];
106;12-12 18:24:49;Timer;4;Stopped timer [Links];
107;12-12 18:24:49;Timer;4;Stopped timer [TokenTimer];
108;12-12 18:24:49;Timer;4;Stopped timer [Roster];
109;12-12 18:24:49;Timer;4;Stopped timer [DelayedLogin];
110;12-12 18:24:49;Timer;4;Stopped timer [Offline];
111;12-12 18:24:49;Timer;4;Stopped timer [Heartbeat];
112;12-12 18:24:49;Timer;4;Stopped timer [StaleLinks];
113;12-12 18:24:49;Timer;4;Stopped timer [Mailbox];
114;12-12 18:25:07;Confederate;4;=====================================;
115;12-12 18:25:07;Confederate;4;  key (string): CtR;
116;12-12 18:25:07;Confederate;4;  initialized (boolean): true;
117;12-12 18:25:07;Confederate;4;  checkedInCount (number): 0;
118;12-12 18:25:07;Confederate;4;  checkedOutCount (number): 0;

**Comment by Chalsean** [comment]
please try beta build 4.2.5 and see if it fixes for you.  on a side note, rolling back to 4.1.24 would have fixed it as well

**Comment by Fyurie** [comment]
Working here on 4.2.5!

I did recommend my players to roll back to 4.1 already just in case this was a little bit involved, but I'm glad to see it's something smaller this time, haha.

Thank you for the quick response!

**Comment by Chalsean** [comment]
np, ill push production 4.2.6 asap

**Comment by TKardinal** [comment]
What was the fix, out of curiosity?  

We have to test I'll get back to you.

**Comment by derekslenk** [comment]
> What was the fix, out of curiosity?

not involved, but the commit for 4.2.5/6 was: https://github.com/Chalsean/XFaction/commit/2f7a16aeb4df2709948dc7e1b4da8347e40c301d

Description says: "Bug fix for confederate w/o raid teams defined"

**Comment by Hyphie24** [comment]
9576;12-12 21:53:52;Unit;2;Failed to parse player note: [?];
9577;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:37: in function `Warn';
9578;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:328: in function `catchBlock';
9579;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch';
9580;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:327: in function `SetNote';
9581;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:97: in function `Initialize';
9582;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:42: in function <Interface/AddOns/XFaction/Handlers/GuildEvent.lua:41>;
9583;12-12 21:53:52;Unit;2;[string "=[C]"]: in function `pcall';
9584;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try';
9585;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:41: in function `_Function';
9586;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Wrappers/EventCollection.lua"]:25: in function <...terface/AddOns/XFaction/Wrappers/EventCollection.lua:21>;
9587;12-12 21:53:52;Unit;2;;
9588;12-12 21:53:52;Unit;2;Failed to parse player note: [?];
9589;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:37: in function `Warn';
9590;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:328: in function `catchBlock';
9591;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch';
9592;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:327: in function `SetNote';
9593;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:97: in function `Initialize';
9594;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:42: in function <Interface/AddOns/XFaction/Handlers/GuildEvent.lua:41>;
9595;12-12 21:53:52;Unit;2;[string "=[C]"]: in function `pcall';
9596;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try';
9597;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:41: in function `_Function';
9598;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Wrappers/EventCollection.lua"]:25: in function <...terface/AddOns/XFaction/Wrappers/EventCollection.lua:21>;
9599;12-12 21:53:52;Unit;2;;
9600;12-12 21:53:52;Unit;2;Failed to parse player note: [?];
9601;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:37: in function `Warn';
9602;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:328: in function `catchBlock';
9603;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch';
9604;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:327: in function `SetNote';
9605;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:97: in function `Initialize';
9606;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:42: in function <Interface/AddOns/XFaction/Handlers/GuildEvent.lua:41>;
9607;12-12 21:53:52;Unit;2;[string "=[C]"]: in function `pcall';
9608;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try';
9609;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:41: in function `_Function';
9610;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Wrappers/EventCollection.lua"]:25: in function <...terface/AddOns/XFaction/Wrappers/EventCollection.lua:21>;
9611;12-12 21:53:52;Unit;2;;
9612;12-12 21:53:52;Unit;2;Failed to parse player note: [?];
9613;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:37: in function `Warn';
9614;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:328: in function `catchBlock';
9615;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch';
9616;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:327: in function `SetNote';
9617;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:97: in function `Initialize';
9618;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:42: in function <Interface/AddOns/XFaction/Handlers/GuildEvent.lua:41>;
9619;12-12 21:53:52;Unit;2;[string "=[C]"]: in function `pcall';
9620;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try';
9621;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:41: in function `_Function';
9622;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Wrappers/EventCollection.lua"]:25: in function <...terface/AddOns/XFaction/Wrappers/EventCollection.lua:21>;
9623;12-12 21:53:52;Unit;2;;
9624;12-12 21:53:52;Unit;2;Failed to parse player note: [?];
9625;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Developer/Logger.lua"]:37: in function `Warn';
9626;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:328: in function `catchBlock';
9627;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:30: in function `catch';
9628;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:327: in function `SetNote';
9629;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Unit/Unit.lua"]:97: in function `Initialize';
9630;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:42: in function <Interface/AddOns/XFaction/Handlers/GuildEvent.lua:41>;
9631;12-12 21:53:52;Unit;2;[string "=[C]"]: in function `pcall';
9632;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Functions/Exception/try-catch-finally.lua"]:12: in function `try';
9633;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Handlers/GuildEvent.lua"]:41: in function `_Function';
9634;12-12 21:53:52;Unit;2;[string "@Interface/AddOns/XFaction/Wrappers/EventCollection.lua"]:25: in function <...terface/AddOns/XFaction/Wrappers/EventCollection.lua:21>;
9635;12-12 21:53:52;Unit;2;

Getting a ton of these popping up in the debuglog with version 4.2.6

**Comment by Chalsean** [comment]
thats a different issue..  are you using teams or alt tagging?

**Comment by Hyphie24** [comment]
We have alt names or player names in general for notes, but had someone mention about the amount of warning messages

**Comment by Chalsean** [comment]
if the person is Lua savvy, they can go to Unit/Unit.lua and change Warn to Trace at line 328

**Comment by Chalsean** [comment]
Fixed in 4.2.6
