### ISSUE TITLE
Confirmation on addon missing

### ISSUE THREAD

**Issue by waggz81** [Chalsean/XFaction#337]
I know we can look at version and see the 0.0.0 but there's a timing issue where it takes a bit to propagate that information. Is there some method we can use to verify the player does not have the addon installed? We're considering a rank for folks without the addon so they can't talk in gchat at all but I don't want to start doing that without some validation if possible.

**Comment by Chalsean** [comment]
keep in mind that addons are incapable of querying for guild rosters of other guilds, so you would only be able to audit the local guild.  then have to hop to another guild and audit again.  a couple ways of doing it is shotgun a ping out and wait for response (can only audit online members) or have the addon update player note that they have the addon installed (can audit offline members)

**Comment by waggz81** [comment]
Yeah that would be expected. I was thinking along the lines of some of the raid tools where you can hit a button and see everyone in the groups version of addons or weakauras installed but realize this might be a bit more heavy with the number of players in the guild. But, you're already transmitting that version data. It would just be nice to be able to somehow query those users showing 0.0.0 in the data broker to confirm they actually don't have it installed or enabled, or if there just is no data yet.

**Comment by waggz81** [comment]
just want to revisit this once you've moved past 5.0 release ;)

**Comment by Chalsean** [comment]
Fixed in 5.1, blank Version means recent login (5m), 0.0.0 means its taken too long and theyre not running addon
