### ISSUE TITLE
duplicate messages cross realm/faction after some time

### ISSUE THREAD

**Issue by waggz81** [Chalsean/XFaction#338]
We have at least two players who have been playing on Illidan Horde that after some time in game they start receiving repeated messages from our Stormrage Alliance chat. Tonight one of them started experiencing this about four hours after logging in, and it isn't current messages it's from ~15 minutes ago. What additional information should I have them gather for you in order to debug?

**Comment by Chalsean** [comment]
there was a couple releases that had introduced a dependency upon ace3 event library.  it totally buckled under load.  its not the actual people seeing the old messages but those forwarding the old messages.  you need to get everyone in the guild up to 4.2.8, which is where i reverted the ace3 changes

**Comment by waggz81** [comment]
I had her do a full reinstall yesterday (deleting addon and lua files form wtf and installing fresh while game exited) before opening the issue but will verify installed version.

**Comment by waggz81** [comment]
confirmed it is happening with 4.2.8

**Comment by Chalsean** [comment]
yeah will occur when someone in the guild is running a version between 4.2.0 and 4.2.8.  there is a cache of message ids to identify duplicates.  ive historically kept that cache lean but with 4.2.12 i increased it to remember a hours worth of ids.  so this should fix duplicate messages from popping up that were less than an hour

**Comment by Chalsean** [comment]
I'm going to mark this fixed in 4.2.12, please let me know if thats not the case and we can reopen
