### ISSUE TITLE
new alt note format not working

### ISSUE THREAD

**Issue by waggz81** [Chalsean/XFaction#345]
When adding notes with the new alt tagging format the main names aren't being listed in the data broker or chat.

`[J-ZtH] Main` is working still.
`[XFa:Main]` is not.

v 4.2.10

**Comment by Chalsean** [comment]
Looks like theres some kind of dependency on XFt being provided with XFa, I'm looking into it

**Comment by Chalsean** [comment]
found the issue, will get a fix out today (4.2.12)

**Comment by Chalsean** [comment]
I'm going to mark this fixed in 4.2.12, please let me know if thats not the case and we can reopen
