### ISSUE TITLE
Friend & Guild online notification not showing

### ISSUE THREAD

**Issue by Hyphie24** [Chalsean/XFaction#360]
Having the online/offline notification enabled for guild in XFaction settings shows guild login like normal. If that setting is turned off but the base wow guild login is checked you get the online friend sound alert, but no text in chat. Was spamming me the other night and I had to spend an hour going through addons to figure out if it was a broken addon or something else, only to find out the box got checked for guild login announcement on base wow options but wasn't seeing text with XFaction on.

Also any toons on friend list when that toon logs in or out you hear the sound like normal, but again no text notification. Turn off Xfaction and works like normal.

If XFaction is enabled, but the toon is not in a guild it will show login/logout like normal. I tested with 3 toons, 1 in a crossguild XFaction used, 1 in a guild with XFaction on but not setup, and a 3rd with XFaction on and no guild. The toon not in a guild would get notification of friend login, but the other 2 toons would not

![image](https://user-images.githubusercontent.com/31455641/221238518-6e6eca71-a75a-4c97-adb4-c07ec042e164.png)
(XFaction enabled)

![image](https://user-images.githubusercontent.com/31455641/221238577-f3a24cb1-b0bf-4a80-8d53-08bd6f5a675a.png)
(XFaction disabled)

I do not get a lua error, don't see anything specifically on _DebugLog that flags that setting (unless I'm missing it) I also did try out the 4.4.3 Beta to see if it was already being addressed but it was not.

Sorry for the long post, but hopefully this helps out some others

**Comment by Chalsean** [comment]
Just to validate, the issues are:

1. Hearing the sound notification when guild mates login with XF login/logout options disabled
2. XF eating the friend notification for login/logout

**Comment by Chalsean** [comment]
I think setting CVar guildMemberNotify will accomplish the guild member part but I need to test it.  Still hunting for bnet friend notification

**Comment by Chalsean** [comment]
No longer needed per submitter
