### ISSUE TITLE
Discord Link gives LUA error

### ISSUE THREAD

**Issue by ValdrakeRG** [Chalsean/XFaction#368]
Message: Interface/AddOns/XFaction/Configuration/General.lua:14: attempt to call method 'Width' (a nil value)
Time: Thu May 18 20:39:48 2023
Count: 1
Stack: Interface/AddOns/XFaction/Configuration/General.lua:14: attempt to call method 'Width' (a nil value)
[string "@Interface/AddOns/XFaction/Configuration/General.lua"]:14: in function `OnShow'
[string "@Interface/FrameXML/StaticPopup.lua"]:5217: in function `StaticPopup_OnShow'
[string "*StaticPopup.xml:247_OnShow"]:1: in function <[string "*StaticPopup.xml:247_OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/StaticPopup.lua"]:5013: in function `StaticPopup_Show'
[string "@Interface/AddOns/XFaction/Configuration/General.lua"]:671: in function <Interface/AddOns/XFaction/Configuration/General.lua:671>
[string "=[C]"]: ?
[string "@Interface/AddOns/XFaction/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua"]:44: in function <...on/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua:42>
[string "@Interface/AddOns/XFaction/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua"]:780: in function <...on/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua:602>
[string "=[C]"]: ?
[string "@Interface/AddOns/XFaction/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...ns/XFaction/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/XFaction/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/XFaction/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...ries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals: self = StaticPopup3 {
 0 = <userdata>
 hideOnEscape = 1
 SubText = FontString {
 }
 ItemFrame = StaticPopup3ItemFrame {
 }
 Border = Frame {
 }
 DarkOverlay = Frame {
 }
 DropDownControl = Frame {
 }
 icon = StaticPopup3AlertIcon {
 }
 moneyFrame = StaticPopup3MoneyFrame {
 }
 text = StaticPopup3Text {
 }
 extraButton = StaticPopup3ExtraButton {
 }
 maxHeightSoFar = 112.999995
 CoverFrame = Frame {
 }
 itemFrame = StaticPopup3ItemFrame {
 }
 data = "https://discord.gg/eternalkingdom"
 AlertIcon = StaticPopup3AlertIcon {
 }
 extraFrame = StaticPopup3ExtraFrame {
 }
 numButtons = 1
 maxWidthSoFar = 320
 button2 = StaticPopup3Button2 {
 }
 LoadingSpinner = Frame {
 }
 moneyInputFrame = StaticPopup3MoneyInputFrame {
 }
 button3 = StaticPopup3Button3 {
 }
 editBox = StaticPopup3EditBox {
 }
 timeleft = 0
 CloseButton = StaticPopup3CloseButton {
 }
 button4 = StaticPopup3Button4 {
 }
 Separator = Texture {
 }
 SpinnerAnim = AnimationGroup {
 }
 onCloseCallback = <function> defined @Interface/FrameXML/StaticPopup.lua:5250
 button1 = StaticPopup3Button1 {
 }
 which = "LINKS"
}
data = "https://discord.gg/eternalkingdom"
(*temporary) = nil
(*temporary) = StaticPopup3EditBox {
 0 = <userdata>
 addHighlightedText = true
 hasAutoComplete = false
 Instructions = FontString {
 }
 autoCompleteParams = <table> {
 }
 width = 130.000076
}
(*temporary) = 280
(*temporary) = "attempt to call method 'Width' (a nil value)"

2nd page LUA error.

Message: Interface/AddOns/XFaction/Configuration/General.lua:14: attempt to call method 'Width' (a nil value)
Time: Thu May 18 20:39:48 2023
Count: 1
Stack: Interface/AddOns/XFaction/Configuration/General.lua:14: attempt to call method 'Width' (a nil value)
[string "@Interface/AddOns/XFaction/Configuration/General.lua"]:14: in function `OnShow'
[string "@Interface/FrameXML/StaticPopup.lua"]:5217: in function `StaticPopup_OnShow'
[string "*StaticPopup.xml:247_OnShow"]:1: in function <[string "*StaticPopup.xml:247_OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/StaticPopup.lua"]:5013: in function `StaticPopup_Show'
[string "@Interface/AddOns/XFaction/Configuration/General.lua"]:671: in function <Interface/AddOns/XFaction/Configuration/General.lua:671>
[string "=[C]"]: ?
[string "@Interface/AddOns/XFaction/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua"]:44: in function <...on/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua:42>
[string "@Interface/AddOns/XFaction/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua"]:780: in function <...on/Libraries/MSA-Ace-3.0/MSA-AceConfigDialog-3.0.lua:602>
[string "=[C]"]: ?
[string "@Interface/AddOns/XFaction/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...ns/XFaction/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/XFaction/Libraries/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/XFaction/Libraries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...ries/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals: self = StaticPopup3 {
 0 = <userdata>
 hideOnEscape = 1
 SubText = FontString {
 }
 ItemFrame = StaticPopup3ItemFrame {
 }
 Border = Frame {
 }
 DarkOverlay = Frame {
 }
 DropDownControl = Frame {
 }
 icon = StaticPopup3AlertIcon {
 }
 moneyFrame = StaticPopup3MoneyFrame {
 }
 text = StaticPopup3Text {
 }
 extraButton = StaticPopup3ExtraButton {
 }
 maxHeightSoFar = 112.999995
 CoverFrame = Frame {
 }
 itemFrame = StaticPopup3ItemFrame {
 }
 data = "https://discord.gg/eternalkingdom"
 AlertIcon = StaticPopup3AlertIcon {
 }
 extraFrame = StaticPopup3ExtraFrame {
 }
 numButtons = 1
 maxWidthSoFar = 320
 button2 = StaticPopup3Button2 {
 }
 LoadingSpinner = Frame {
 }
 moneyInputFrame = StaticPopup3MoneyInputFrame {
 }
 button3 = StaticPopup3Button3 {
 }
 editBox = StaticPopup3EditBox {
 }
 timeleft = 0
 CloseButton = StaticPopup3CloseButton {
 }
 button4 = StaticPopup3Button4 {
 }
 Separator = Texture {
 }
 SpinnerAnim = AnimationGroup {
 }
 onCloseCallback = <function> defined @Interface/FrameXML/StaticPopup.lua:5250
 button1 = StaticPopup3Button1 {
 }
 which = "LINKS"
}
data = "https://discord.gg/eternalkingdom"
(*temporary) = nil
(*temporary) = StaticPopup3EditBox {
 0 = <userdata>
 addHighlightedText = true
 hasAutoComplete = false
 Instructions = FontString {
 }
 autoCompleteParams = <table> {
 }
 width = 130.000076
}
(*temporary) = 280
(*temporary) = "attempt to call method 'Width' (a nil value)"

**Comment by Chalsean** [comment]
Unable to reproduce, please reopen ticket if still seeing this issue.
