### ISSUE TITLE
Cross Faction Guilds

### ISSUE THREAD

**Issue by Tolkien-Pendergast** [Chalsean/XFaction#369]
Hey Chalsean! 

Is there a limitation with XFaction and Cross Faction guilds? When setting up you need to assign the guild to a faction, and we are finding that Horde members in an Alliance guild can't chat across server (Cluster seems to be okay, but still confirming this)

For example: Frostmourne is Xfg:3725:A:GuildName:GuildNickname and I would imagine the specification of the A means Horde cannot chat?

Do you know if this is correct? Is there a workaround to this or is it just a current limitation?

Love the addon though, it's been great.

**Comment by Tolkien-Pendergast** [comment]
This makes sense, thanks so much for taking the time to reply to me :)

"Bnet will still solve the problem" interests me, maybe we just need to set up more, is it possible to add BOTH H and A to the same guild via the guild info string? So it would be: Xfg:3725:H:Guild:Guild and Xfg:3725:H:Guild:Guild. Might give this a whirl, though I'd imagine our other officer has tried this.

Having said all this, in your FAQS you have stated to try and keep factions on the same realm. Once again really appreciate this addon and what it's done for you guild, thanks so much!

**Comment by Chalsean** [comment]
My apologies this is sooo late in responding.  Been dealing with employment issues most of this year but things have finally settled down.  Did you get XFaction working for your guild?

**Comment by Tolkien-Pendergast** [comment]
Hi Chals,

All good. Hope everything is going okay for you now.

Yes we got it working :) it’s been working beautifully from what I can tell. Madmaori will be able to confirm (think he is on this thread too)

Thanks!

Sent from my iPhone

On 2 Oct 2023, at 23:50, Chalsean ***@***.***> wrote:

﻿

My apologies this is sooo late in responding. Been dealing with employment issues most of this year but things have finally settled down. Did you get XFaction working for your guild?
