### ISSUE TITLE
Ho to opn in game /slash code

### ISSUE THREAD

**Issue by Thirteen75** [Chalsean/XFaction#375]
Hi,

I just downloaded the EK Xfaction addon in hopes it will be everything I am looking for.  I literally don't even know ho to open it in game, there is no minimap icon :( help is much apricated

**Comment by Chalsean** [comment]
You can open the options from either the addon compartment or under Options, Addons, XFaction.

**Comment by Thirteen75** [comment]
Hey Thanks I figured that out prior :)  sure wish we understood how to make this work lol we have a guild an alt guild same realm and sister guilds on other realms and this addon seemed so promising to solve our needs..but we cannot make it work :(

**Comment by Chalsean** [comment]
Hey did you get this working for your guilds?
