### ISSUE TITLE
No guild chat v4.7.4

### ISSUE THREAD

**Issue by Hyphie24** [Chalsean/XFaction#378]
Updated to version 4.7.4 last night, it has stopped showing guild chat on my server Aerie Peak. lists no guild members on and nothing has been changed besides updating the addon. Attached is DebugLog

![image](https://github.com/Chalsean/XFaction/assets/31455641/bb37eda8-c750-416e-9af1-e20411e64d3c)

Reverted to version 4.6.10 and guild chat working as intended

![image](https://github.com/Chalsean/XFaction/assets/31455641/7becb6ed-38eb-48d5-9271-758b78d310ae)

**Comment by waggz81** [comment]
Getting reports of this on our confederation as well.

**Comment by Chalsean** [comment]
Hmm strange.  There's several on the build in EK confed.  I'll need to park a toon one of your guilds to troubleshoot

**Comment by Chalsean** [comment]
Try 4.7.6 and see if it works for you now

**Comment by Hyphie24** [comment]
This seems to be fixed in 4.7.6

**Comment by Chalsean** [comment]
thx for letting me know, ill close the ticket
