### ISSUE TITLE
Wrong Faction Icon possible guild tag

### ISSUE THREAD

**Issue by Hyphie24** [Chalsean/XFaction#383]
Version 4.7.16, on a horde toon shows fellow horde as alliance. On alliance it shows normal horde

![image](https://github.com/Chalsean/XFaction/assets/31455641/3f4ff195-5d6d-4a13-9b39-a6c0419e22a9)

![image](https://github.com/Chalsean/XFaction/assets/31455641/9f7a0e89-6e57-45fc-9568-60fee8366f9a)

![image](https://github.com/Chalsean/XFaction/assets/31455641/e535ad7a-c170-4445-87e2-f7f3bfa815f3)

Polazkal (me) Horde seeing Lokosha (also horde) as alliance

Guild tag not showing when checked (possibly disabled?) going by a guildmate, they had no guild tag, guild name box was checked, downgraded to 4.7.12 it showed tag, updated to 4.7.16 and stayed.

**Comment by Chalsean** [comment]
finally tracked this down to the chat message logic pulling the faction from the guild tag information.  back when guilds were faction aligned.  should be an easy-ish fix but ill need to get into the serialization code

**Comment by Chalsean** [comment]
Fix will be in 4.8.16, currently in beta testing as 4.8.15.
