### ISSUE TITLE
Support: Unable to see alliance characters on Illidan from Stormrage

### ISSUE THREAD

**Issue by lyledouglass** [Chalsean/XFaction#393]
Hello - member of ZTH and DJs who you've worked with before, bit of an odd issue I can't figure out. Might be related to https://github.com/Chalsean/XFaction/issues/388 but the wording doesn't quite match.

We have our main Stormrage guild and some sister guilds that have mostly alliance players, but some horde and that all works fine. We also have a linked guild on Illidan that's mostly Horde, and it seamlessly works as well. The issue we're encountering is if you're an _alliance_ player in the Illidan guild, you don't get any XFaction communication, only standard guild chat.

Nothing pops up in bugsack, and here's the DebugLog. Nothing really stands out to me. Lmk if I can provide any other info!

EDIT: forgot to mention - we do have active BNet links when we are testing this!

| ID| Time| Cat| Vrb| Message |
| --- | --- | --- | --- | ---  |
| 1| 03-18 15:38:16| | | Log for 'XFaction' created |
| 2| 03-18 15:38:16| | | Format for log 'XFaction' is 'default' |
| 3| 03-18 15:38:16| Event| 4| Started event listener [AddonEvent] for [ADDON_LOADED] |
| 4| 03-18 15:38:16| Event| 3| Registered to receive [AddonEvent:ADDON_LOADED] events |
| 5| 03-18 15:38:16| Initialize| 3| XFaction version [4.8.14] |
| 6| 03-18 15:38:16| RegionCollection| 3| Initialized player region [1:US] |
| 7| 03-18 15:38:16| FactionCollection| 3| Initialized faction [1:Alliance] |
| 8| 03-18 15:38:16| FactionCollection| 3| Initialized faction [2:Horde] |
| 9| 03-18 15:38:16| FactionCollection| 3| Initialized faction [3:Neutral] |
| 10| 03-18 15:38:16| RealmCollection| 3| Initialized player realm [57:Illidan] |
| 11| 03-18 15:38:16| Realm| 4| ------------------------------------- |
| 12| 03-18 15:38:16| Realm| 4|   key (string): Illidan |
| 13| 03-18 15:38:16| Realm| 4|   id (number): 57 |
| 14| 03-18 15:38:16| Realm| 4|   name (string): Illidan |
| 15| 03-18 15:38:16| Realm| 4|   initialized (boolean): true |
| 16| 03-18 15:38:16| Realm| 4|   apiName (nil): nil |
| 17| 03-18 15:38:16| Realm| 4|   isTargeted (boolean): false |
| 18| 03-18 15:38:16| Realm| 4|   connectedRealmCount (number): 0 |
| 19| 03-18 15:38:16| TeamCollection| 3| Initialized team [?:Unknown] |
| 20| 03-18 15:38:16| Event| 3| Registered to receive [Achievement:ACHIEVEMENT_EARNED] events |
| 21| 03-18 15:38:16| Event| 3| Registered to receive [Friend:BN_FRIEND_INFO_CHANGED] events |
| 22| 03-18 15:38:16| Event| 3| Registered to receive [GuildChat:CHAT_MSG_GUILD] events |
| 23| 03-18 15:38:16| Event| 3| Registered to receive [Roster:GUILD_ROSTER_UPDATE] events |
| 24| 03-18 15:38:16| Event| 4| Started event listener [CraftOrder] for [CRAFTINGORDERS_ORDER_PLACEMENT_RESPONSE] |
| 25| 03-18 15:38:16| Event| 3| Registered to receive [CraftOrder:CRAFTINGORDERS_ORDER_PLACEMENT_RESPONSE] events |
| 26| 03-18 15:38:16| Event| 4| Started event listener [CanRequestOrders] for [CRAFTINGORDERS_CAN_REQUEST] |
| 27| 03-18 15:38:16| Event| 3| Registered to receive [CanRequestOrders:CRAFTINGORDERS_CAN_REQUEST] events |
| 28| 03-18 15:38:16| Event| 3| Registered to receive [Mythic:CHALLENGE_MODE_COMPLETED] events |
| 29| 03-18 15:38:16| Event| 3| Registered to receive [Spec:ACTIVE_TALENT_GROUP_CHANGED] events |
| 30| 03-18 15:38:16| Event| 3| Registered to receive [Instance:PLAYER_ENTERING_WORLD] events |
| 31| 03-18 15:38:16| Event| 3| Registered to receive [Level:PLAYER_LEVEL_CHANGED] events |
| 32| 03-18 15:38:16| Event| 3| Registered to receive [Profession:SKILL_LINES_CHANGED] events |
| 33| 03-18 15:38:16| Event| 3| Registered to receive [Zone:ZONE_CHANGED_NEW_AREA] events |
| 34| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Pandaria] |
| 35| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Draenor] |
| 36| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Broken Isles] |
| 37| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Zandalar] |
| 38| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Kul Tiras] |
| 39| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Argus] |
| 40| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Eastern Kingdoms] |
| 41| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Kalimdor] |
| 42| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Outland] |
| 43| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Northrend] |
| 44| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Nazjatar] |
| 45| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Dragon Isles] |
| 46| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Ohn'ahran Plains] |
| 47| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [Resonant Peaks] |
| 48| 03-18 15:38:16| ZoneCollection| 3| Initialized continent [The Shadowlands] |
| 49| 03-18 15:38:16| ZoneCollection| 3| Initialized zone [?] |
| 50| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [168:EB] |
| 51| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [464:RISE] |
| 52| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [463:FALL] |
| 53| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [456:TT] |
| 54| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [198:DHT] |
| 55| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [244:AD] |
| 56| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [199:BRH] |
| 57| 03-18 15:38:16| DungeonCollection| 3| Initialized dungeon [248:WM] |
| 58| 03-18 15:38:16| Timer| 4| Started timer [LoginGuild] for [1] seconds |
| 59| 03-18 15:38:16| ExpansionCollection| 3| Initialized expansion [1:Retail] |
| 60| 03-18 15:38:16| ExpansionCollection| 3| Initialized expansion [2:Classic] |
| 61| 03-18 15:38:16| Initialize| 3| WoW client version [Retail:10.2.5] |
| 62| 03-18 15:38:16| AddonEvent| 3| Addon is loaded and enabled [XFaction] |
| 63| 03-18 15:38:16| AddonEvent| 3| Initializing cache |

**Comment by Chalsean** [comment]
just realized i never responded to this, my sincerest apologies.  did you get this working?

**Comment by lyledouglass** [comment]
I'm not sure - I'll have to follow up and let you know!

**Comment by Chalsean** [comment]
there are significant changes deploying in 5.0.2 to enable cross realm viz.  im going to close this out as the logic has changed so much, it would be impossible to reverse find this.  if it continues to be an issue please let me know
