### ISSUE TITLE
Support: Set up help needed

### ISSUE THREAD

**Issue by Katt910** [Chalsean/XFaction#407]
Hello. Sorry to bother you but my guild member and I have recently downloaded your add on xfaction about a week ago. I am not the smartest in this area so I apologize. 

We cant seem to get it to work between the guilds. Its not showing guild chat for either of us. Its only the chat we are having issues with at this point. We got everything else working. And it did create a channel but neither of us can see the guild chat and our channels are never the same. Like he can be on channel 6 and im on channel 5. 

Is there anyway you could help us with this issue and tell us what we are doing wrong? I would greatly appreciate it. Thanks!

**Comment by Chalsean** [comment]
sure i can help.  usually what is easiest is for me is to place some toon in your guild so i can troubleshoot.  would you be open to that?

**Comment by Katt910** [comment]
yes i would be! thank you so much.  the guild is lucid dreams on alexstraza. its our ali guild. our horde guild is on terokar and called easily distracted.

**Comment by Chalsean** [comment]
okay i have to run over and help my parents today but i can be online tomorrow afternoon.  my discord is Chals (Chalsean#5295)

**Comment by Katt910** [comment]
That would be awesome. Thank you. If you don’t mind I’ll have Mario my guild member who’s been helping me add you on discord. He’s the tech person lol. I’ll send a request when I get on before raid tonight as well. I’m a stay at home mom so I’m free anytime. Just send me a dm. Thank you again!

**Comment by Chalsean** [comment]
This was done in June, just getting around to closing ticket
