### ISSUE TITLE
Links between Guilds not maintaining

### ISSUE THREAD

**Issue by fewyn** [Chalsean/XFaction#413]
We are currently having a ton of issues maintaining any kinds of links even with multiple members being Bnet friends and this is happening for both factions. This is 5 guilds across both Horde and Alliance. I've even checked the data broker and can see I'm linked to a few people from the other faction but not seeing anyone from our other guilds connecting.

Is there any specific info you need to see what might be going on? This has been working for awhile since we moved over from Greenwall back in October but we've only started seeing this issue in the last few weeks.

**Comment by Chalsean** [comment]
Sorry this was entirely my fault.  Was prepping for TWW changes and was unaware of the breakdown until brought to my attention over the weekend.  The release 4.16.2 is a repackage of 4.10.2, which to my knowledge was the last good build.  Please give that one a shot and let me know.  Unfortunately it does require everyone to be off builds 4.11-4.14

**Comment by fewyn** [comment]
> Sorry this was entirely my fault. Was prepping for TWW changes and was unaware of the severity of the breakdown until brought to my attention over the weekend. The release 4.16.2 is a repackage of 4.10.2, which to my knowledge was the last good build. Please give that one a shot and let me know. Unfortunately it does require everyone to be off builds 4.11-4.14

Yep everything seems fine now!
