### ISSUE TITLE
Player has gone offline message won't stop

### ISSUE THREAD

**Issue by wsfrazier** [Chalsean/XFaction#414]
I have the online/offline settings unchecked/disabled... But I am still getting messages when members in other connected guilds going offline. Completely flushed out my UI and cvars from scratch and still happening. No other chat addons and not using elvui.

Am I the only one seeing this?

**Comment by Hyphie24** [comment]
Same thing for me, but I've noticed it only on one character. I'm not sure if it was from the changes before those changes where reverted back. I turned the guild notifications on, left on for a while, then turned off so far in 15 minutes, I haven't seen them pop back up, but still watching

**Comment by wsfrazier** [comment]
Didn't fix it for me :( 

left it on for a few hours before setting back off again

**Comment by Chalsean** [comment]
try resetting your profile.  options / xfaction / profile / i think theres a reset button but i cant remember the exact text

**Comment by Hyphie24** [comment]
I'll give it a shot now
