### ISSUE TITLE
Cross-realm & cross-faction guild chat

### ISSUE THREAD

**Issue by Hyphie24** [Chalsean/XFaction#417]
Noticed today, not sure if this is a known issue, but we're having an issue with someone on another realm, our case Earthen Ring, joining the guild on Aerie Peak, they can see guild chat of their normal guild chat, but can not see any guild chat outside of that.

Character is Horde on Earthen Ring, joins Alliance guild on Aerie Peak. Can talk to guild on Aerie Peak, but can not talk outside that guild in the federation. Federation has been working since 11.0 with no changes to code

**Comment by TKardinal** [comment]
Mine is the character in question.  Data included below. 

No broker data visible.

<img width="481" alt="NoBrokerData" src="https://github.com/user-attachments/assets/070d7745-86a9-4c0d-bd7d-3524596ce008">

Debug Log below:

[DebugLog-XFaction-Kardinal-EarthenRing.txt](https://github.com/user-attachments/files/16474359/DebugLog-XFaction-Kardinal-EarthenRing.txt)

**Comment by Chalsean** [comment]
Ciao guys, yes this is a known issue.  Its requiring a significant amount of code changes to the networking layer of the addon.  It likely will be unstable as I hammer the logic into place.  I have scheduled PTO the week prior to TWW launch (week of the 19th) to release the new version, as historically that is the lightest week of an xpac.  Expect several patches to roll out that week as I work on it.

**Comment by Hyphie24** [comment]
Figured it as much, since it's a lot to change. 

If you need anyone to test it let us know

**Comment by TKardinal** [comment]
> Ciao guys, yes this is a known issue. Its requiring a significant amount of code changes to the networking layer of the addon. It likely will be unstable as I hammer the logic into place. I have scheduled PTO the week prior to TWW launch (week of the 19th) to release the new version, as historically that is the lightest week of an xpac. Expect several patches to roll out that week as I work on it.

Indeed, we had a feeling that was the case.  But best to give the feedback.  Happy to help when the time is right.

**Comment by Chalsean** [comment]
Fixed in 5.0.2
